sistempondok/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from santri import views as santri_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', user_views.MyLoginView.as_view(template_name= 'users/login2.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name= 'users/login2.html'), name='logout'),
    path('register/', user_views.register, name='register'),
    path('liststaff/', user_views.list_staff, name='list_staff'),
    path('staff/<int:pk>/delete', user_views.delete_staff, name='staff-delete'),
    path('createstaff/', user_views.create_staff, name='create_staff'),
    path('createsuperuser/', user_views.create_superuser, name='create_superuser'),
    path('profile/', user_views.profile, name='profile'),

    # santri
    path('', user_views.index, name='home'),
    path('search/', user_views.search, name='search'),
    path('santrilist/', santri_views.SantriListView.as_view(), name='santri-list'),
    path('santricreate/', santri_views.SantriCreateView.as_view(), name='santri-create'),
    path('santri/<int:pk>/update/', santri_views.SantriUpdateView.as_view(), name='santri-update'),
    path('santri/<int:pk>/', santri_views.SantriDetailView.as_view(), name='santri-detail'),
    path('santri/<int:pk>/delete/', santri_views.SantriDeleteView.as_view(), name='santri-delete'),
    
    # anggota santri
    path('santri/<int:santri>/anggotakeluargacreate/', santri_views.AnggotaKeluargaCreateView.as_view(), name='anggotakeluarga-create'),
    path('santri/<int:santri>/anggotakeluarga/<int:anggotakeluarga>/update/', santri_views.update_anggotakeluarga, name='anggotakeluarga-update'),
    path('santri/<int:santri>/anggotakeluarga/<int:anggotakeluarga>/delete/', santri_views.delete_anggotakeluarga, name='anggotakeluarga-delete'),

    # santri keluar
    path('keluarlist/', santri_views.KeluarListView.as_view(), name='keluar-list'),
    path('santri/<int:pk>/keluarcreate/', santri_views.KeluarCreateView.as_view(), name='keluar-create'),
    path('santri/<int:santri>/keluar/<int:keluar>/update/', santri_views.update_keluar, name='keluar-update'),
    path('santri/<int:santri>/keluar/<int:keluar>/invoice/', santri_views.keluar_invoice, name='keluar-invoice'),

    #santri pulang
    path('pulanglist/', santri_views.PulangListView.as_view(), name='pulang-list'),
    path('santri/<int:pk>/pulangcreate/', santri_views.PulangCreateView.as_view(), name='pulang-create'),
    path('santri/<int:santri>/pulang/<int:pulang>/update/', santri_views.update_pulang, name='pulang-update'),
    path('santri/<int:santri>/pulang/<int:pulang>/invoice/', santri_views.pulang_invoice, name='pulang-invoice'),

    # santri sambang
    path('sambanglist/', santri_views.SambangListView.as_view(), name='sambang-list'),
    path('santri/<int:pk>/sambangcreate/', santri_views.SambangCreateView.as_view(), name='sambang-create'),
    path('santri/<int:santri>/sambang/<int:sambang>/update/', santri_views.update_sambang, name='sambang-update'),
    path('santri/<int:santri>/sambang/<int:sambang>/invoice/', santri_views.sambang_invoice, name='sambang-invoice'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

santri/models/anggota_keluarga.py
from django.db import models
from django.urls import reverse
from django.core.validators import RegexValidator
from .santri import Santri
from PIL import Image

class AnggotaKeluarga(models.Model):
    santri = models.ForeignKey(Santri, on_delete=models.CASCADE, null=True, blank=True)
    nama = models.CharField(max_length=50)
    pilihan_gender = (
        ('L', 'Laki-Laki'),
        ('P', 'Perempuan')
    )
    gender = models.CharField(max_length=20, choices=pilihan_gender)
    pilihan_status = (
        ('Ayah', 'Ayah'), ('Ibu', 'Ibu'), ('Kakak', 'Kakak'), ('Adik', 'Adik'),
        ('Ayah Tiri', 'Ayah Tiri'), ('Ibu Tiri', 'Ibu Tiri'), ('Kakak Tiri', 'Kakak Tiri'), ('Adik Tiri', 'Adik Tiri')
    )
    status = models.CharField(max_length=10, choices=pilihan_status)
    id_tag = models.CharField(max_length=30, null=True, blank=True)
    regex = RegexValidator(regex=r'^\d[0-9 -]{4,50}$', message="format berupa: '999999/ 999 999 / 999-999', min:5 digit,maks: 50 digit" )
    no_nik = models.CharField(validators=[regex], max_length=55)
    no_kk = models.CharField(validators=[regex], max_length=55)
    pilihan_agama = (
        ('Islam', 'Islam'), 
        ('Kristen', 'Kristen'), 
        ('Katholik', 'Katholik'), 
        ('Hindu', 'Hindu'), 
        ('Budha', 'Budha'), 
        ('Konghucu', 'Konghucu')
    )
    agama = models.CharField(max_length=10, choices=pilihan_agama)
    phone = RegexValidator(regex=r'^\+?\d[0-9 -]{4,20}$', message="format berupa: '+999999 / +999 999 / +999-999, min:5 digit, maks:20 digit" )
    no_telp = models.CharField(validators=[phone], max_length=23 , null=True, blank=True)
    alamat = models.TextField(max_length=300)
    provinsi = models.CharField(max_length=50)
    kota = models.CharField(max_length=50)
    kecamatan = models.CharField(max_length=50)
    image = models.ImageField(default='default.jpg', upload_to='kk_pics')

    def __str__(self):
        return self.nama

    def get_absolute_url(self):
        return reverse('santri-detail', kwargs={'pk':self.santri.id})

    def save(self, *args, **kwargs):
            
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

santri/models/keluar.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta
from .santri import Santri

class Keluar(models.Model):
    staff = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    no_invoice = models.CharField(max_length=300, null=True, blank=True)
    santri = models.ForeignKey(Santri, on_delete=models.CASCADE, null=True, blank=True)
    pilihan_keluar = (
        ('Periksa di Rumah Sakit', 'Periksa di Rumah Sakit'),
        ('Periksa di Puskesmas', 'Periksa di Puskesmas'),
        ('Belanja di Pasar', 'Belanja di Pasar'),
        ('Lain-Lain', 'Lain-Lain')
    )
    keperluan = models.CharField(max_length=30, choices=pilihan_keluar)
    keterangan = models.TextField(max_length=999, null=True, blank=True)
    start_time = models.DateTimeField(auto_now_add=True)
    pilihan_status = (
        ('Started', 'Masih keluar'),
        ('Ended', 'Selesai')
    )
    status = models.CharField(max_length=20, choices=pilihan_status)
    pilihan_durasi = (
        (timedelta(minutes=15), '15 menit'),
        (timedelta(minutes=30), '30 menit'),
        (timedelta(hours=1), '1 jam'),
        (timedelta(hours=2), '2 jam'),
        (timedelta(hours=3), '3 jam'),
        (timedelta(hours=5), '5 jam'),
        (timedelta(hours=10), '10 jam'),
    )
    masa_durasi = models.DurationField(null=True, blank=True, choices=pilihan_durasi)
    durasi_habis = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    sisa_waktu = models.DurationField(null=True, blank=True)

    def __str__(self):
        return self.keperluan

santri/forms.py
from django import forms
from .models.santri import Santri
from .models.anggota_keluarga import AnggotaKeluarga
from .models.keluar import Keluar
from .models.pulang import Pulang


class SantriForm(forms.ModelForm):
    class Meta:
        model = Santri
        fields = [
            'image', 'nama', 'gender', 'id_tag', 'no_induk', 'no_nik', 'no_kk', 'tempat_lahir', 
            'tanggal_lahir', 'agama', 'anak_ke', 'dari', 'no_telp', 'pendidikan_terakhir', 
            'provinsi', 'kota', 'kecamatan', 'alamat', 
        ]

class AnggotaKeluargaForm(forms.ModelForm):
    
    class Meta:
        model = AnggotaKeluarga
        fields = ['nama', 'gender', 'id_tag', 'status', 'no_nik', 'no_kk', 'agama', 'no_telp', 'alamat', 'provinsi', 'kota', 'kecamatan', 'image']
        labels = {
            'no_telp': 'No Telepon',
        }

class KeluarForm(forms.ModelForm):
    class Meta:
        model = Keluar
        fields = ['keperluan', 'keterangan', 'masa_durasi', 'status']

class PulangForm(forms.ModelForm):
    class Meta:
        model = Pulang
        fields = ['keperluan', 'keterangan', 'masa_durasi', 'anggotakeluarga']

    def __init__(self, *args, **kwargs):
        santri = kwargs.pop('user') 
        super(PulangForm, self).__init__(*args, **kwargs)
        self.fields['anggotakeluarga'].queryset = AnggotaKeluarga.objects.filter(santri_id=5)

santri/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models.santri import Santri
from .models.anggota_keluarga import AnggotaKeluarga
from .models.keluar import Keluar
from .models.pulang import Pulang
from .models.sambang import Sambang
from .forms import SantriForm, AnggotaKeluargaForm, KeluarForm
from django.utils import timezone
from django.urls import reverse_lazy

# Santri
class SantriListView(LoginRequiredMixin, ListView):
    model = Santri
    context_object_name = 'para_santri'
    ordering = '-tanggal_masuk'

class SantriDetailView(LoginRequiredMixin, DetailView):
    model = Santri 
    context_object_name = 'santri'

class SantriCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Santri
    form_class = SantriForm
    success_message = 'Data santri berhasil dibuat'

class SantriUpdateView(LoginRequiredMixin ,SuccessMessageMixin, UpdateView):
    model = Santri
    form_class = SantriForm
    success_message = 'Data santri berhasil diupdate'

class SantriDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Santri
    success_message = "Data Santri sudah dihapus"
    success_url = reverse_lazy('santri-list')


# Anggota Santri
class AnggotaKeluargaCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = AnggotaKeluarga
    fields = [
        'nama', 'gender', 'id_tag', 'status', 'no_nik', 'no_kk', 'agama', 'no_telp', 'alamat',
        'provinsi', 'kota', 'kecamatan', 'image'
    ]
    success_message = "Data Anggota Keluarga telah dibuat"

    def form_valid(self, form):
        form.instance.santri = Santri.objects.get(id=self.kwargs['santri'])
        return super(AnggotaKeluargaCreateView, self).form_valid(form)

# update anggotakeluarga 
@login_required
def update_anggotakeluarga(request, santri, anggotakeluarga):
    anggotakeluarga = get_object_or_404(AnggotaKeluarga, id=anggotakeluarga)
    form = AnggotaKeluargaForm(instance=anggotakeluarga)
    if request.method == 'POST':
        form = AnggotaKeluargaForm(request.POST, request.FILES, instance=anggotakeluarga)
        print(form)
        if form.is_valid():
            form.save()
            messages.success(request, 'Data anggota keluarga berhasil diperbarui')
            return redirect('santri-detail', pk=santri)
    return render(request, 'santri/anggotakeluarga_form.html', {'form':form})

# delete anggotakeluarga
@login_required
def delete_anggotakeluarga(request, santri, anggotakeluarga):
    if request.method == 'POST':
        get_object_or_404(AnggotaKeluarga, id=anggotakeluarga).delete()
        messages.success(request, 'Data anggota keluarga berhasil dihapus')
        return redirect('santri-detail', santri)

class KeluarCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Keluar
    fields = [
        'keperluan', 'keterangan', 'masa_durasi'
    ]
    success_message = "Data santri keluar telah dibuat"
    success_url = reverse_lazy('keluar-list')

    def get_context_data(self, *args, **kwargs):
        form = super(KeluarCreateView, self).get_context_data(*args, **kwargs)
        form['santri'] = Santri.objects.get(id=self.kwargs['pk'])
        return form
    
    def form_valid(self, form):
        form.instance.santri = Santri.objects.get(id=self.kwargs['pk'])
        return super(KeluarCreateView, self).form_valid(form)

class KeluarListView(LoginRequiredMixin, ListView):
    model = Keluar
    context_object_name = 'santri_keluar'
    ordering = '-start_time'

@login_required
def update_keluar(request, santri, keluar):
    Keluar.objects.filter(id=keluar).update(end_time=timezone.now())
    obj = Keluar.objects.get(id=keluar)
    Keluar.objects.filter(id=keluar).update(
            no_invoice = f'INV/{obj.end_time.strftime("%Y%m%d")}/{obj.id}/01/{obj.santri.no_induk}',
            sisa_waktu = obj.durasi_habis - obj.end_time,
            staff = request.user,
            status='Ended'
    )
    messages.success(request, f'Santri {Santri.objects.get(id=santri)} telah kembali')
    return redirect('keluar-list')

def keluar_invoice(request, santri, keluar):
    obj = Keluar.objects.get(pk=keluar)
    return render(request, 'santri/keluar_invoice.html', {'obj':obj})

class PulangCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Pulang
    fields = ['keperluan', 'keterangan', 'masa_durasi', 'anggotakeluarga']
    success_message = "Data santri Pulang telah dibuat"
    success_url = reverse_lazy('pulang-list')

    def get_context_data(self, *args, **kwargs):
        form = super(PulangCreateView, self).get_context_data(*args, **kwargs)
        form['santri'] = Santri.objects.get(id=self.kwargs['pk'])
        form['form'].fields['anggotakeluarga'].queryset = AnggotaKeluarga.objects.filter(santri=form['santri'])
        return form
    
    def form_valid(self, form):
        form.instance.santri = Santri.objects.get(id=self.kwargs['pk'])
        return super(PulangCreateView, self).form_valid(form)

class PulangListView(LoginRequiredMixin, ListView):
    model = Pulang
    context_object_name = 'santri_pulang'
    ordering = '-start_time'

@login_required
def update_pulang(request, santri, pulang):
    Pulang.objects.filter(id=pulang).update(end_time=timezone.now())
    obj = Pulang.objects.get(id=pulang)
    Pulang.objects.filter(id=pulang).update(
            no_invoice = f'INV/{obj.end_time.strftime("%Y%m%d")}/{obj.id}/02/{obj.santri.no_induk}',
            sisa_waktu = obj.durasi_habis - obj.end_time,
            staff = request.user,
            status='Ended'
    )
    #invoice format INV/TAHUNBULANTANGGAL/NOID/NOPULANG/NOINDUK
    messages.success(request, f'Santri {Santri.objects.get(id=santri)} telah kembali')
    return redirect('pulang-list')

def pulang_invoice(request, santri, pulang):
    obj = Pulang.objects.get(pk=pulang)
    return render(request, 'santri/pulang_invoice.html', {'obj':obj})


class SambangCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Sambang
    fields = ['penjenguk', 'menginap', 'keterangan', 'masa_durasi']
    success_message = "Data santri sambang telah dibuat"
    success_url = reverse_lazy('sambang-list')

    def get_context_data(self, *args, **kwargs):
        form = super(SambangCreateView, self).get_context_data(*args, **kwargs)
        form['santri'] = Santri.objects.get(id=self.kwargs['pk'])
        form['form'].fields['penjenguk'].queryset = AnggotaKeluarga.objects.filter(santri=form['santri'])
        return form
    
    def form_valid(self, form):
        form.instance.santri = Santri.objects.get(id=self.kwargs['pk'])
        return super(SambangCreateView, self).form_valid(form)

class SambangListView(LoginRequiredMixin, ListView):
    model = Sambang
    context_object_name = 'santri_sambang'
    ordering = '-start_time'

@login_required
def update_sambang(request, santri, sambang):
    Sambang.objects.filter(id=sambang).update(end_time=timezone.now())
    obj = Sambang.objects.get(id=sambang)
    Sambang.objects.filter(id=sambang).update(
            no_invoice = f'INV/{obj.end_time.strftime("%Y%m%d")}/{obj.id}/03/{obj.santri.no_induk}',
            sisa_waktu = obj.durasi_habis - obj.end_time,
            staff = request.user,
            status='Ended'
    )
    #invoice format INV/TAHUNBULANTANGGAL/NOID/NOKELUAR/NOINDUK
    messages.success(request, f'Santri {Santri.objects.get(id=santri)} sudah selesai disambang')
    return redirect('sambang-list')

def sambang_invoice(request, santri, sambang):
    obj = Sambang.objects.get(pk=sambang)
    return render(request, 'santri/sambang_invoice.html', {'obj':obj})

def invoice(request):
    return render(request, 'santri/invoice.html')

santri/templates/santri/home.html
{% extends "santri/base.html" %}
{% block content %}

    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}

santri/templates/santri/keluar_form.html
{% extends "dashboard/blank.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="card shadow border-primary">
        <div class="card-header border-primary">
            <h5 class="m-0 font-weight-bold text-primary">Form Santri Keluar</h5>
        </div>
        <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="container content-section">
                            <form method="POST">
                                {% csrf_token %}
                                <legend class="border-bottom mb-4">Santri {{ santri }} Keluar</legend>
                                    <div class="form-row">
    
                                        <div class="form-group col-md-6">
                                            {{ form.keperluan|as_crispy_field }}
                                        </div>
                                        <div class="form-group col-md-6">
                                            {{ form.masa_durasi|as_crispy_field }}
                                        </div>
                                        <div class="form-group col-md-12">
                                            {{ form.keterangan|as_crispy_field }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-outline-info" type="submit">Tambah</button>
                                    </div>
                                </form>
                            
                        </div>
                      </div>
                    </div>
        </div>
</div>


{% endblock %}

santri/templates/santri/pulang_list.html
{% extends "dashboard/blank.html" %}
{% block content %}

{% if santri_pulang %}
<div class="card shadow border-primary">
    <div class="card-header border-primary">
        <h3 class="card-title">Santri Pulang
        </h3>
    </div>
    <div class="card-body">
        <div class="content-section">
            <table class="table table-striped table-bordered">
              <thead>
                <tr class="bg-light table-success">
                  <th scope="col">Nama Santri</th>
                  <th scope="col">Keperluan</th>
                  <th scope="col">Status</th>
                  <th scope="col">Masa Durasi</th>
                  <th scope="col">Waktu Pulang</th>
                  <th scope="col">Deadline</th>
                  <th scope="col">Waktu Kembali</th>
                </tr>
              </thead>
              <tbody>
                {% for santri in santri_pulang %}
                        <tr>
                            <th scope='row'>
                                <img src="{{santri.santri.image.url }}" class="rounded-circle account-img img-thumbnail mr=5" alt="avatar"
                                style="width: 50px;
                                height: auto;">
                              {% if santri.end_time %}
                                <a href="{% url 'pulang-invoice' santri.santri.pk santri.pk %}">{{ santri.santri.nama }}</a>
                              {% else %}
                                {{ santri.santri.nama }}
                              {% endif %}
                            </th>
                            <td>{{ santri.keperluan }}</td>
                            <td>
                              {% if santri.get_status_display == 'Selesai' %}
                              <span class="badge badge-pill badge-success">{{ santri.get_status_display }}</span>
                                {% else %}
                                <span class="badge badge-pill badge-danger">{{ santri.get_status_display }}</span>
                                {% endif %}
                            </td>
                                
                            <td>{{ santri.get_masa_durasi_display }}</td>
                            <td>{{ santri.start_time|date:"d/m/Y" }}
                                    <p style="color:#2f56c7">{{ santri.start_time|date:"H:i" }}</p>
                            </td>
                            <td>{{ santri.durasi_habis|date:"d/m/Y" }}
                                    <p style="color:red">{{ santri.durasi_habis|date:"H:i" }}</p>
                            </td>
                            <td> 
                              {% if santri.end_time %}
                                {{ santri.end_time|date:"d/m/Y" }}
                                <p style="color:green">{{ santri.end_time|date:"H:i" }}</p>
                              {% else %}
                                <a href="{% url 'pulang-update' santri.santri.pk santri.pk %}" class="btn btn-outline-danger">
                                    <span class="icon text-white-300"><i class="fas fa-arrow-right fa-2x"></i></span>
                                </a>
                              {% endif %}
                              </td>
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>
                      
                  </div>
          
              {% if is_paginated %}
          
                {% if page_obj.has_previous %}
                  <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
          
                {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                  {% endif %}
                {% endfor %}
          
                {% if page_obj.has_next %}
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
          
              {% endif %}
    </div>
</div>
{% else %}
  <h5 class="text-center">Tidak Ada Santri yang Pulang</h5>
{% endif%}


{% endblock content %}

santri/templates/santri/sambang_list.html
{% extends "dashboard/blank.html" %}
{% block content %}

{% if santri_sambang %}
<div class="card shadow border-primary">
    <div class="card-header border-primary">
        <h3 class="card-title">Santri Sambang
        </h3>
    </div>
    <div class="card-body">
        <div class="content-section">
            <table class="table table-striped table-bordered">
              <thead>
                <tr class="bg-light table-info">
                  <th scope="col">Nama Santri</th>
                  <th scope="col">Nama Penjenguk</th>
                  <th scope="col">Status</th>
                  <th scope="col">Masa Durasi</th>
                  <th scope="col">Waktu Sambang</th>
                  <th scope="col">Deadline</th>
                  <th scope="col">Selesai Sambang</th>
                </tr>
              </thead>
              <tbody>
                {% for santri in santri_sambang %}
                        <tr>
                            <th scope='row'>
                                <img src="{{santri.santri.image.url }}" class="rounded-circle account-img img-thumbnail mr=5" alt="avatar"
                                style="width: 50px;
                                height: auto;">
                                {% if santri.end_time %}
                                  <a href="{% url 'sambang-invoice' santri.santri.pk santri.pk %}">{{ santri.santri.nama }}</a>
                                {% else %}
                                  {{ santri.santri.nama }}
                                {% endif %}
                              </th>
                            <td>{{ santri.penjenguk }} ({{ santri.status_penjenguk }})</td>
                            <td>
                              {% if santri.get_status_display == 'Selesai' %}
                              <span class="badge badge-pill badge-success">{{ santri.get_status_display }}</span>
                                {% else %}
                                <span class="badge badge-pill badge-danger">{{ santri.get_status_display }}</span>
                                {% endif %}
                            </td>
                                
                            <td>{{ santri.get_masa_durasi_display }}</td>
                            <td>{{ santri.start_time|date:"d/m/Y" }}
                                    <p style="color:#2f56c7">{{ santri.start_time|date:"H:i" }}</p>
                            </td>
                            <td>{{ santri.durasi_habis|date:"d/m/Y" }}
                                    <p style="color:red">{{ santri.durasi_habis|date:"H:i" }}</p>
                            </td>
                            <td> 
                              {% if santri.end_time %}
                                {{ santri.end_time|date:"d/m/Y" }}
                                <p style="color:green">{{ santri.end_time|date:"H:i" }}</p>
                              {% else %}
                                <a href="{% url 'sambang-update' santri.santri.pk santri.pk %}" class="btn btn-outline-danger">
                                    <span class="icon text-white-300"><i class="fas fa-arrow-right fa-2x"></i></span>
                                </a>
                              {% endif %}
                              </td>
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>
                      
                  </div>
          
              {% if is_paginated %}
          
                {% if page_obj.has_previous %}
                  <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
          
                {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                  {% endif %}
                {% endfor %}
          
                {% if page_obj.has_next %}
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
          
              {% endif %}
    </div>
</div>
{% else %}
  <h5 class="text-center">Tidak Ada Santri yang disambang</h5>
{% endif%}


{% endblock content %}